apiVersion: v1
kind: Service
metadata:
  name: hacker-news-frontend-service
spec:
  type: NodePort
  selector:
    app: hacker-news-frontend
  ports:
    - port: 3000
      targetPort: 80
      nodePort: 31200
